jQuery.nowrap       = jQuery.fn.nowrap;
jQuery.cycle        = jQuery.fn.cycle;
jQuery.onlyDigits   = jQuery.fn.onlyDigits;
jQuery.int          = jQuery.fn.int   = jQuery.parseInt   = jQuery.fn.parseInt;
jQuery.float        = jQuery.fn.float = jQuery.parseFloat = jQuery.fn.parseFloat;
jQuery.popup        = jQuery.fn.popup;
jQuery.src          = jQuery.fn.src;
jQuery.href         = jQuery.fn.href;
jQuery.disable      = jQuery.fn.disable;
jQuery.enable       = jQuery.fn.enable;
jQuery.hash         = jQuery.fn.hash;
jQuery.preload      = jQuery.fn.preload;
jQuery.toCenter     = jQuery.fn.toCenter;
jQuery.ending       = jQuery.fn.ending;
jQuery.removeSpaces = jQuery.fn.removeSpaces;
jQuery.reverse      = jQuery.fn.reverse;
jQuery.percentage   = jQuery.fn.percentage;
jQuery.breakdown    = jQuery.fn.breakdown;
jQuery.genCount     = jQuery.fn.genCount;